ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
platform :ios, '15.1'

# Explicitly specify the Xcode project
project 'Lissnify.xcodeproj'


require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!
use_frameworks! :linkage => :static

target 'Lissnify' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'glog'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        end
      end
    end
  end
end
